CREATE TABLE CLIENTE(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    DS_NOME VARCHAR(1000),
    DS_SOBRENOME VARCHAR(1000),
    NR_DOCUMENTO VARCHAR(50),

    PRIMARY KEY (ID)
);

INSERT INTO CLIENTE(DS_NOME, DS_SOBRENOME, NR_DOCUMENTO)
VALUES ('CONSUMIDOR', 'FINAL', '00000000000')